//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreSale.Properties
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocapplepay_msdyn_MerchantCapabilities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Debit", 0, "#0000ff")]
		Debit = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Credit", 1, "#0000ff")]
		Credit = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("3D Secure", 2, "#0000ff")]
		_3DSecure = 192350002,
	}
}